### ISSUE TITLE
Embedded svg image render issues

### ISSUE THREAD

**Issue by Brooooooklyn** [typst/svg2pdf#18]
### Input SVG

![font-emoji](https://user-images.githubusercontent.com/3468483/188361525-7bf7a5dc-86e0-47aa-9041-160e72e65d66.svg)

### Output PDF

[font-emoji.pdf](https://github.com/typst/svg2pdf/files/9486698/font-emoji.pdf)

**Comment by LaurenzV** [comment]
#34 fixes this.
