### ISSUE TITLE
no any text

### ISSUE THREAD

**Issue by Lishen1** [typst/svg2pdf#43]
`svg2pdf output.svg`
[output.pdf](https://github.com/typst/svg2pdf/files/13187495/output.pdf)
![output](https://github.com/typst/svg2pdf/assets/6782809/bb35db2e-5257-4e53-8504-1bd0bec6dcbe)
[output.zip](https://github.com/typst/svg2pdf/files/13187511/output.zip)

**Comment by LaurenzV** [comment]
[map.pdf](https://github.com/typst/svg2pdf/files/13187782/map.pdf)
Seems to work fine for me, I think the issue probably is that the font couldn't be found on your system? I guess we should add some kind of warning in case that happens.

**Comment by Lishen1** [comment]
it is. font from svg was not installed

**Comment by LaurenzV** [comment]
Closing this in favor of #65.
